#!/usr/bin/env ruby

require "json"

# evil hack to make Chef use the current directory
File.open('local_config.json', 'w') do |file|
  JSON.dump({
    'run_list' => ['role[local]'],
    'snowbots' => {
      'workspace' => Dir.pwd,
      'user' => ENV['USERNAME']
    }
  }, file)
end

system 'sudo chef-solo -c local_config.rb'

