#!/usr/bin/env ruby

require "json"

USERNAME = ENV['USERNAME']
WORKSPACE = Dir.pwd
LOCAL_CONFIG_FILE_NAME = 'local_config.json'

if /^\s*$/ =~ USERNAME then
  abort "error: $USERNAME='#{USERNAME}' environment variable is empty. aborting.\n"
end

print "user: #{USERNAME}\n"
print "workspace: #{WORKSPACE}\n\n"

print "writing config file: #{LOCAL_CONFIG_FILE_NAME}..."

# evil hack to make Chef use the current directory
File.open(LOCAL_CONFIG_FILE_NAME, 'w') do |file|
  JSON.dump({
    'run_list' => ['role[local]'],
    'snowbots' => {
      'workspace' => WORKSPACE,
      'user' => USERNAME
    }
  }, file)
end

print "done.\n"

CHEF_COMMAND = "sudo chef-solo -c local_config.rb"

print "running: '#{CHEF_COMMAND}'...\n"
system CHEF_COMMAND
print "done.\n"

